### ISSUE TITLE
missing templates

### ISSUE THREAD

**Issue by simahawk** [deliverance/Deliverance#1]
hi,
paster_templates/ are not included during installation so that when you try to create a deliverance project you get:

OSError: [Errno 2] No such file or directory: '/home/simahawk/dev/deliverance/lib/python2.6/site-packages/Deliverance-0.4.1-py2.6.egg/deliverance/paster-templates/deliverance'

still, if you try to run deliverance-proxy without creating a project you get:

IOError: [Errno 2] No such file or directory: '/home/simahawk/dev/deliverance/lib/python2.6/site-packages/Deliverance-0.4.1-py2.6.egg/deliverance/editor/editor_template.html'

Into the virtualenv I tried both with "easy_install Deliverance" and "setup.py install" after cloning it from this repository.

Those templates are of course there in the source but they are not pulled in on installation.

**Comment by simahawk** [comment]
"cp -R Deliverance/deliverance/paster-templates/ lib/python2.6/site-packages/Deliverance-0.4.1-py2.6.egg/deliverance/."

and 

"cp Deliverance/deliverance/editor/*.html lib/python2.6/site-packages/Deliverance-0.4.1-py2.6.egg/deliverance/editor/."

and also

cp -r Deliverance/deliverance/media/ lib/python2.6/site-packages/Deliverance-0.4.1-py2.6.egg/deliverance/.

did the trick

now it runs.

**Comment by ejucovy** [comment]
Hmm, something must have broken after the move to Git.  I just added a MANIFEST.in file which I think will force it to include all the necessary static data: b38f24472942149da3d04b3658ef4de79d934d1e

Can you try it again?

**Comment by simahawk** [comment]
just tried to create a project and to run it: they worked both!! :)
thanks

**Comment by ejucovy** [comment]
Great - I just tagged and uploaded a new 0.4.2 release with this fix.  Thanks for reporting this.
